version: '3'

services:
  web_feedback_progress:
    platform: linux/x86_64
    build: .
    volumes:
      - ./web_feedback_progress:/project/web_feedback_progress
    ports:
      - 3000:3000
      - 3001:3001